---
kind: pipeline
name: python3.6

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: python:3.6
  commands:
  - make install
  - make lint

- name: test
  image: python:3.6
  commands:
  - make install
  - COV_REPORT_DEST=/tmp/artifacts/coverage.xml make coverage
  volumes:
  - name: artifacts
    path: /tmp/artifacts

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - /tmp/artifacts/coverage.xml
    required: true
    token:
      from_secret: codecov-token
  volumes:
  - name: artifacts
    path: /tmp/artifacts

volumes:
- name: artifacts
  temp: {}

trigger:
  event:
  - push
  - tag

---
kind: pipeline
name: python3.7

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: python:3.7
  commands:
  - make install lint test

trigger:
  event:
  - push
  - tag

---
kind: pipeline
name: python3.5

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: python:3.5.3
  commands:
  - make install lint test

trigger:
  event:
  - push
  - tag

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.6
  commands:
  - make build
  volumes:
  - name: artifacts
    path: /tmp/artifacts

- name: pypi
  image: plugins/pypi
  settings:
    distributions:
    - sdist
    - bdist_wheel
    password:
      from_secret: pypi-secret
    username: release-bot
  volumes:
  - name: artifacts
    path: /tmp/artifacts

volumes:
- name: artifacts
  temp: {}

trigger:
  event:
  - tag
  status:
  - success

depends_on:
- python3.5
- python3.6
- python3.7

...
